version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elasticsearch-elk
    restart: unless-stopped
    build:
      context: elasticsearch/
    environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        - xpack.ml.enabled=false
        - xpack.watcher.enabled=false
        - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml:ro
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kibana-elk
    restart: unless-stopped
    environment:
      - xpack.security.enabled=false
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/kibana.yml:ro
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.8.0
    container_name: logstash-elk
    restart: unless-stopped
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
volumes:
  elasticsearch_data:

networks:
  default:
    name: br_dashboard
    external: true