{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taipei-city-dashboard.fullname" . }}-frontend
  labels:
    {{- include "taipei-city-dashboard.frontend.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.frontend.service.annotations }}
    {{- range $k, $v := . }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  {{- with .Values.frontend.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.frontend.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "taipei-city-dashboard.frontend.selectorLabels" . | nindent 4 }}
{{- end }}